# -*- coding: utf-8 -*-
"""
This family file was auto-generated by $Id: 81013ef7ef131adfec131ac6f657a3856b7e9356 $
Configuration parameters:
  url = 'URL_where_the_wiki_is_located'
  name = 'Name_of_the_Wiki'

Please do not commit this to the Git repository!
"""

from pywikibot import family
from pywikibot.tools import deprecated


class Family(family.Family):
    def __init__(self):
        family.Family.__init__(self)
        self.name = 'Name_of_the_Wiki'
        self.langs = {
            'en': 'URL_where_the_wiki_is_located',
        }

    def scriptpath(self, code):
        return {
            'en': '/mediawiki',
        }[code]

    @deprecated('APISite.version()')
    def version(self, code):
        return {
            'en': u'1.26.0',
        }[code]

    def protocol(self, code):
        return {
            'en': u'https',
        }[code]

    def ignore_certificate_error(self, code):
        return True  # has an expired certificate.
